name = "Myrovh's Modpack (fabric)"
author = "myrovh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8647953636bd08a54dfdad871d79c9872af0c5812f1e688085ddc601c9fdbb16"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
