name = "Myrovh's Modpack (fabric)"
author = "myrovh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30c60e0c4973b941adc7c99692ae8c1971db8572b5a0d2185f76ba0607d34fe6"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
