name = "Myrovh's Modpack (fabric)"
author = "myrovh"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eeb1de4ec416d80fc2290d7c2dbffa94b34fbcdb83f29b25be92dbfa4aa06e7b"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
